name: Node CI
on:
    pull_request:
        branches:
            - master
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            # - name: Checkout
            #   uses: actions/checkout@v2
            # - name: Configure AWS Credentials
            #   uses: aws-actions/configure-aws-credentials@v1
            #   with:
            #       aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
            #       aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            #       aws-region: ap-southeast-2
            - name: ci
              uses: MechanicalRock/aws-codebuild-run-build@uat
              env:
                  AWS_REGION: ap-southeast-2
                  GITHUB_SECRET: ${{ secrets.GITHUB_TOKEN }}
              with:
                  endpoint: ${{ secrets.ENDPOINT }}
                  use-credentials: false
                  project-name: test-project


    # test:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Configure AWS Credentials
    #           uses: aws-actions/configure-aws-credentials@v1
    #           with:
    #               aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
    #               aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    #               aws-region: ap-southeast-2
    #         - name: test
    #           uses: matt-tyler/aws-codebuild-run-build@master
    #           env:
    #               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #           with:
    #               project-name: Test-myapp-Node
    # lint:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Configure AWS Credentials
    #           uses: aws-actions/configure-aws-credentials@v1
    #           with:
    #               aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
    #               aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    #               aws-region: ap-southeast-2
    #         - name: lint
    #           uses: matt-tyler/aws-codebuild-run-build@master
    #           env:
    #               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #           with:
    #               project-name: Lint-myapp-Node
